# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mrcnn-text-segmentation',
                'doc_host': 'https://sethdroberts.github.io',
                'git_url': 'https://github.com/sethdroberts/mrcnn-text-segmentation',
                'lib_path': 'mrcnn_text_segmentation'},
  'syms': {'mrcnn_text_segmentation.core': {'mrcnn_text_segmentation.core.foo': ('core.html#foo', 'mrcnn_text_segmentation/core.py')}}}
