"""Processing and sorting dataset"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data.ipynb.

# %% auto 0
__all__ = ['get_filepaths', 'convert_tif_jpg']

# %% ../nbs/01_data.ipynb 5
def get_filepaths(suff_str, dataset_path):
    '''Gets list of filepaths for all files in dir with same suffix'''
    dataset_path = Path(dataset_path)
    file_path = list(dataset_path.glob(f'*.{suff_str}'))
    return file_path

# %% ../nbs/01_data.ipynb 9
def convert_tif_jpg(path_list):
    '''Converts tifs into jpgs from list of filepaths'''
    for filepath in path_list:
        im = Image.open(filepath)
        rgb_im = im.convert("RGB")
        rgb_im.save(f"{filepath.stem}.jpg")

